from PyQt5 import QtCore

TM_EVENT_EXCEPTION = QtCore.QEvent.User+1
TM_EVENT_ON_ADD_CONTEXT = QtCore.QEvent.User+2
TM_EVENT_ON_UPDATE_CONTEXT = QtCore.QEvent.User+3
TM_EVENT_ON_DELETE_CONTEXT = QtCore.QEvent.User+4
TM_EVENT_ON_ADD_OBJECT = QtCore.QEvent.User+5
TM_EVENT_ON_UPDATE_OBJECT = QtCore.QEvent.User+6
TM_EVENT_ON_DELETE_OBJECT = QtCore.QEvent.User+7