from PyQt5 import QtCore

TM_EVENT_EXCEPTION = QtCore.QEvent.User+1
TM_EVENT_ON_ADD_CONTEXT = QtCore.QEvent.User+2
TM_EVENT_ON_UPDATE_CONTEXT = QtCore.QEvent.User+3
TM_EVENT_ON_DELETE_CONTEXT = QtCore.QEvent.User+4